name: Deploy to GCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: sharp-leaf-451416-r4

      - name: Deploy to Compute Engine
        run: |
          gcloud compute ssh --zone "us-central1-f" "instance-20260220-140252" \
            --project "sharp-leaf-451416-r4" \
            --quiet \
            --command "sudo chown -R \$USER:\$USER /home/user/backend && cd /home/user/backend && git pull origin main && pip install -r requirements.txt && sudo systemctl restart fastapi-backend"
